# Generated by Django 3.0.4 on 2020-03-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200311_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nameis',
            new_name='author',
        ),
    ]
